title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  There will be pictures and there will be some blogs about some random thoughts!
  I promise (as long as I don't get lazy and stop trying).
  It is a great learning experience.

# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
#Google search results) and in your feed.xml site description.

baseurl: "/flukymusings" # the subpath of your site, e.g. /blog
url: "https://haroldchoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com


twitter_username: bagelsarelife
github_username:  haroldchoo

# Build settings
# permalink: pretty

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass


baseurl: "/flukymusings" # the subpath of your site, e.g. /blog
url: "https://haroldchoo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
